### ISSUE TITLE
FATAL ERROR: uninitialized constant App::WebsitePage

### ISSUE THREAD

**Issue by shanko** [waxxio/waxx#2]
I have created a demo site as per the instructions in README and tried to navigate to:

http://localhost:7777/usr#

I am getting this error: `FATAL ERROR: uninitialized constant App::WebsitePage` which I could track down to the following code snippet in **/app/usr/html.rb:**

```
  def login(x, return_to:"/")
    %(
      <div class="container">
      <h1>Client Portal</h1>
      <div class="row">
        <div class="col-md-4">#{login_form(x, return_to:return_to)}</div>
        <div class="col-md-8">#{App::WebsitePage.by_uri(x, uri:"/portal")['content']}</div>
      </div>
      </div>
    )
  end
```

Here is what I see on the page:

<img width="1435" alt="Screen Shot 2019-08-10 at 10 13 49 AM" src="https://user-images.githubusercontent.com/10062/62823588-fe080c80-bb57-11e9-9181-a94e6c2e23ef.png">

**Comment by dfitzpat** [comment]
In my apps I normally have content stored in the database. But the default installation does not include that but unfortunately is trying to get the content. 

Please delete this line: `<div class="col-md-8">#{App::WebsitePage.by_uri(x, uri:"/portal")['content']}</div>`

Hopefully this week I will post a complete example site.

**Comment by shanko** [comment]
Deleting the line did the trick. Thank you very much!  

I will hold off reporting more issues till you get a chance to post the complete example site as most of them may be irrelevant by then. 

Pretty excited to try it all out in a real project.

**Comment by dfitzpat** [comment]
Version 0.2.0 fixes this issue.
